In [1]:
import open3d as o3d
import vtk
import numpy as np

In [2]:
bus_o3d = o3d.io.read_triangle_mesh("bus.stl")
bus_o3d.compute_vertex_normals()
bus_o3d

geometry::TriangleMesh with 224376 points and 74792 triangles.

In [3]:
bus_o3d.get_max_bound() - bus_o3d.get_min_bound()

array([ 2.56912069, 11.24986124,  2.89770126])

In [40]:
bus_pcd = o3d.geometry.PointCloud()
bus_pcd.points = o3d.utility.Vector3dVector(np.asarray(bus_o3d.vertices))
o3d.visualization.draw_geometries([bus_pcd, bus_o3d], mesh_show_wireframe=True)

# Subdivide Mesh

In [5]:
np.asarray(bus_o3d.vertices)

array([[-1.51806152, -0.67451322, -0.57115453],
       [-1.51806152, -0.67451322, -0.2865701 ],
       [-1.51806152, -0.72531313, -0.57115453],
       ...,
       [-2.04584932,  4.43263578,  0.4721885 ],
       [-1.89237523,  4.42421436,  0.47975662],
       [-2.04584932,  4.42074919,  0.48373345]])

In [6]:
np.asarray(bus_o3d.triangles)

array([[     0,      1,      2],
       [     3,      4,      5],
       [     6,      7,      8],
       ...,
       [224367, 224368, 224369],
       [224370, 224371, 224372],
       [224373, 224374, 224375]], dtype=int32)

In [7]:
tri1 = o3d.geometry.TriangleMesh()
tri2 = o3d.geometry.TriangleMesh()

In [8]:
points = np.asarray([[1, 0, 0],
                     [0, 0, 1],
                     [-1, 0, 0],
                     [0, 1, 0]])

triangle1 = np.array([[0, 1, 2]], dtype=np.int32)
triangle2 = np.array([[0, 2, 3]], dtype=np.int32)

In [9]:
tri1.vertices = o3d.utility.Vector3dVector(points)
tri1.triangles = o3d.utility.Vector3iVector(triangle1)
tri2.vertices = o3d.utility.Vector3dVector(points)
tri2.triangles = o3d.utility.Vector3iVector(triangle2)

In [10]:
color1 = np.asarray([1.0, 0.706, 0.0], dtype=np.float64)
color2 = np.asarray([1.0, 0.0, 0.0], dtype=np.float64)
tri1.paint_uniform_color(color1)
tri2.paint_uniform_color(color2)

geometry::TriangleMesh with 4 points and 1 triangles.

In [12]:
np.asarray(tri1.vertices)

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [13]:
tri1_subdiv = tri1.subdivide_midpoint(number_of_iterations=1)
np.asarray(tri1_subdiv.vertices)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [-1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.5,  0. ,  0.5],
       [-0.5,  0. ,  0.5],
       [ 0. ,  0. ,  0. ]])

In [14]:
np.asarray(tri1_subdiv.triangles)

array([[0, 4, 6],
       [4, 1, 5],
       [5, 2, 6],
       [4, 5, 6]], dtype=int32)

In [15]:
tri_mid = tri.subdivide_midpoint(number_of_iterations=1)
tri_loop = tri.subdivide_loop(number_of_iterations=1)

NameError: name 'tri' is not defined

In [16]:
o3d.visualization.draw_geometries([tri1, tri2], mesh_show_wireframe=True)

# Get Vertices of Mesh Triangles

In [59]:
triangles = np.asarray(bus_o3d.triangles)
triangles

array([[     0,      1,      2],
       [     3,      4,      5],
       [     6,      7,      8],
       ...,
       [224367, 224368, 224369],
       [224370, 224371, 224372],
       [224373, 224374, 224375]], dtype=int32)

In [60]:
vertices = np.asarray(bus_o3d.vertices)
vertices

array([[-1.51806152, -0.67451322, -0.57115453],
       [-1.51806152, -0.67451322, -0.2865701 ],
       [-1.51806152, -0.72531313, -0.57115453],
       ...,
       [-2.04584932,  4.43263578,  0.4721885 ],
       [-1.89237523,  4.42421436,  0.47975662],
       [-2.04584932,  4.42074919,  0.48373345]])

In [61]:
tri = np.asarray([[list(vertices[p]) for p in triangle] for triangle in triangles])
tri[:5]

array([[[-1.51806152, -0.67451322, -0.57115453],
        [-1.51806152, -0.67451322, -0.2865701 ],
        [-1.51806152, -0.72531313, -0.57115453]],

       [[-1.51806152, -0.52855664, -0.62503606],
        [-1.51806152, -0.58243817, -0.57115453],
        [-1.51806152, -0.67451322, -0.57115453]],

       [[-1.51806152, -0.67451322, -0.57115453],
        [-1.51806152, -0.72531313, -0.57115453],
        [-1.51806152, -0.52855664, -0.62503606]],

       [[-1.51806152, -0.72531313, -0.2865701 ],
        [-1.51806152, -0.72531313, -0.57115453],
        [-1.51806152, -0.67451322, -0.2865701 ]],

       [[-1.51806152, -0.82056314, -0.57115453],
        [-1.51806152, -0.87444472, -0.62503606],
        [-1.51806152, -0.72531313, -0.57115453]]])

In [32]:
tri[0, :, 0].sum() / 3

-2.2770922780036926

In [33]:
tri[0, :, 1].sum() / 2

-1.0371697843074799

In [34]:
tri[0, :, 2].sum() / 2

-0.7144395858049393

In [62]:
tri_center = np.array([np.sum(tri[:, :, 0], axis=1)/3, np.sum(tri[:, :, 1], axis=1)/3, np.sum(tri[:, :, 2], axis=1)/3]).T
tri_center

array([[-1.51806152, -0.69144652, -0.47629306],
       [-1.51806152, -0.59516935, -0.58911504],
       [-1.51806152, -0.64279433, -0.58911504],
       ...,
       [-1.69662543,  4.42957417,  0.47498579],
       [-1.80720973,  4.42120425,  0.48361361],
       [-1.99469129,  4.42586644,  0.47855952]])

In [63]:
pcd_tri_center = o3d.geometry.PointCloud()
pcd_tri_center.points = o3d.utility.Vector3dVector(tri_center)

In [ ]:
o3d.visualization.draw_geometries([pcd_tri_center, bus_o3d], mesh_show_wireframe=True)

# Compute Area of Mesh Triangles

In [20]:
tri[:, 0, :] - tri[:, 1, :]

array([[ 0.        ,  0.        , -0.28458443],
       [ 0.        ,  0.05388153, -0.05388153],
       [ 0.        ,  0.05079991,  0.        ],
       ...,
       [ 0.16539586,  0.00918484, -0.00839186],
       [ 0.08913946, -0.00826693,  0.01074722],
       [-0.15347409,  0.00842142, -0.00756812]])

In [21]:
((tri[:, 0, :] - tri[:, 1, :]) / np.linalg.norm(tri[:, 0, :] - tri[:, 1, :], axis=1)[:, None])

array([[ 0.        ,  0.        , -1.        ],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       ...,
       [ 0.99718285,  0.05537601, -0.05059508],
       [ 0.98862834, -0.09168686,  0.11919536],
       [-0.99728975,  0.05472322, -0.04917839]])

In [23]:
np.dot([1, 2, 3], [1, 2, 3])

14

In [24]:
np.dot([3, 4, 5], [1, 2, 3])

26

In [25]:
np.einsum('ij,ij->i', [[1, 2, 3],[3, 4, 5]], [[1, 2, 3], [1, 2, 3]])

array([14, 26])

In [26]:
vector_1 = tri[:, 0, :] - tri[:, 1, :]
vector_2 = tri[:, 0, :] - tri[:, 2, :]

unit_vector_1 = vector_1 / np.linalg.norm(vector_1, axis=1)[:, None]
unit_vector_2 = vector_2 / np.linalg.norm(vector_2, axis=1)[:, None]
dot_product = np.einsum('ij,ij->i',unit_vector_1, unit_vector_2)
angle = np.arccos(dot_product)

angle

array([1.57079633, 0.43175611, 2.7879506 , ..., 0.07507961, 2.83089987,
       1.49721104])

# Adaptive Mesh Triangles Subdivision