In [1]:
import open3d as o3d
import vtk
import numpy as np

In [2]:
bus_o3d = o3d.io.read_triangle_mesh("bus.stl")
bus_o3d.compute_vertex_normals()
bus_o3d

geometry::TriangleMesh with 224376 points and 74792 triangles.

In [3]:
bus_o3d.get_max_bound() - bus_o3d.get_min_bound()

array([ 2.56912069, 11.24986124,  2.89770126])

In [40]:
bus_pcd = o3d.geometry.PointCloud()
bus_pcd.points = o3d.utility.Vector3dVector(np.asarray(bus_o3d.vertices))
o3d.visualization.draw_geometries([bus_pcd, bus_o3d], mesh_show_wireframe=True)

# Subdivide Mesh

In [5]:
np.asarray(bus_o3d.vertices)

array([[-1.51806152, -0.67451322, -0.57115453],
       [-1.51806152, -0.67451322, -0.2865701 ],
       [-1.51806152, -0.72531313, -0.57115453],
       ...,
       [-2.04584932,  4.43263578,  0.4721885 ],
       [-1.89237523,  4.42421436,  0.47975662],
       [-2.04584932,  4.42074919,  0.48373345]])

In [6]:
np.asarray(bus_o3d.triangles)

array([[     0,      1,      2],
       [     3,      4,      5],
       [     6,      7,      8],
       ...,
       [224367, 224368, 224369],
       [224370, 224371, 224372],
       [224373, 224374, 224375]], dtype=int32)

In [7]:
tri1 = o3d.geometry.TriangleMesh()
tri2 = o3d.geometry.TriangleMesh()

In [8]:
points = np.asarray([[1, 0, 0],
                     [0, 0, 1],
                     [-1, 0, 0],
                     [0, 1, 0]])

triangle1 = np.array([[0, 1, 2]], dtype=np.int32)
triangle2 = np.array([[0, 2, 3]], dtype=np.int32)

In [9]:
tri1.vertices = o3d.utility.Vector3dVector(points)
tri1.triangles = o3d.utility.Vector3iVector(triangle1)
tri2.vertices = o3d.utility.Vector3dVector(points)
tri2.triangles = o3d.utility.Vector3iVector(triangle2)

In [10]:
color1 = np.asarray([1.0, 0.706, 0.0], dtype=np.float64)
color2 = np.asarray([1.0, 0.0, 0.0], dtype=np.float64)
tri1.paint_uniform_color(color1)
tri2.paint_uniform_color(color2)

geometry::TriangleMesh with 4 points and 1 triangles.

In [12]:
np.asarray(tri1.vertices)

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [13]:
tri1_subdiv = tri1.subdivide_midpoint(number_of_iterations=1)
np.asarray(tri1_subdiv.vertices)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [-1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.5,  0. ,  0.5],
       [-0.5,  0. ,  0.5],
       [ 0. ,  0. ,  0. ]])

In [14]:
np.asarray(tri1_subdiv.triangles)

array([[0, 4, 6],
       [4, 1, 5],
       [5, 2, 6],
       [4, 5, 6]], dtype=int32)

In [15]:
tri_mid = tri.subdivide_midpoint(number_of_iterations=1)
tri_loop = tri.subdivide_loop(number_of_iterations=1)

NameError: name 'tri' is not defined

In [16]:
o3d.visualization.draw_geometries([tri1, tri2], mesh_show_wireframe=True)

# Get Vertices of Mesh Triangles

In [59]:
triangles = np.asarray(bus_o3d.triangles)
triangles

array([[     0,      1,      2],
       [     3,      4,      5],
       [     6,      7,      8],
       ...,
       [224367, 224368, 224369],
       [224370, 224371, 224372],
       [224373, 224374, 224375]], dtype=int32)

In [60]:
vertices = np.asarray(bus_o3d.vertices)
vertices

array([[-1.51806152, -0.67451322, -0.57115453],
       [-1.51806152, -0.67451322, -0.2865701 ],
       [-1.51806152, -0.72531313, -0.57115453],
       ...,
       [-2.04584932,  4.43263578,  0.4721885 ],
       [-1.89237523,  4.42421436,  0.47975662],
       [-2.04584932,  4.42074919,  0.48373345]])

In [61]:
tri = np.asarray([[list(vertices[p]) for p in triangle] for triangle in triangles])
tri[:5]

array([[[-1.51806152, -0.67451322, -0.57115453],
        [-1.51806152, -0.67451322, -0.2865701 ],
        [-1.51806152, -0.72531313, -0.57115453]],

       [[-1.51806152, -0.52855664, -0.62503606],
        [-1.51806152, -0.58243817, -0.57115453],
        [-1.51806152, -0.67451322, -0.57115453]],

       [[-1.51806152, -0.67451322, -0.57115453],
        [-1.51806152, -0.72531313, -0.57115453],
        [-1.51806152, -0.52855664, -0.62503606]],

       [[-1.51806152, -0.72531313, -0.2865701 ],
        [-1.51806152, -0.72531313, -0.57115453],
        [-1.51806152, -0.67451322, -0.2865701 ]],

       [[-1.51806152, -0.82056314, -0.57115453],
        [-1.51806152, -0.87444472, -0.62503606],
        [-1.51806152, -0.72531313, -0.57115453]]])

In [83]:
tri_centroid = np.array([np.sum(tri[:, :, 0], axis=1)/3, np.sum(tri[:, :, 1], axis=1)/3, np.sum(tri[:, :, 2], axis=1)/3]).T
tri_centroid

array([[-1.51806152, -0.69144652, -0.47629306],
       [-1.51806152, -0.59516935, -0.58911504],
       [-1.51806152, -0.64279433, -0.58911504],
       ...,
       [-1.69662543,  4.42957417,  0.47498579],
       [-1.80720973,  4.42120425,  0.48361361],
       [-1.99469129,  4.42586644,  0.47855952]])

In [93]:
pcd_tri_centroid = o3d.geometry.PointCloud()
pcd_tri_centroid.points = o3d.utility.Vector3dVector(tri_centroid)

In [85]:
o3d.visualization.draw_geometries([pcd_tri_centroid, bus_o3d], mesh_show_wireframe=True)

# Set External View Points

In [86]:
np.asarray(pcd_tri_centroid.points)

array([[-1.51806152, -0.69144652, -0.47629306],
       [-1.51806152, -0.59516935, -0.58911504],
       [-1.51806152, -0.64279433, -0.58911504],
       ...,
       [-1.69662543,  4.42957417,  0.47498579],
       [-1.80720973,  4.42120425,  0.48361361],
       [-1.99469129,  4.42586644,  0.47855952]])

In [69]:
max_bound = bus_o3d.get_max_bound()
max_bound

array([0.15117578, 5.98305464, 1.40197897])

In [70]:
min_bound = bus_o3d.get_min_bound()
min_bound

array([-2.41794491, -5.2668066 , -1.49572229])

In [71]:
top_view = ((max_bound[0]+min_bound[0])/2, (max_bound[1]+min_bound[1])/2, max_bound[2] + 10)
top_view

(-1.1333845630288124, 0.3581240177154541, 11.401978969573975)

In [94]:
top_view = np.array([top_view])
top_view

array([[-1.13338456,  0.35812402, 11.40197897]])

In [95]:
pcd_top_view = o3d.geometry.PointCloud()
pcd_top_view.points = o3d.utility.Vector3dVector(top_view)
o3d.visualization.draw_geometries([pcd_top_view, bus_o3d], mesh_show_wireframe=True)

# Load Mesh Using VTK

In [102]:
# load mesh into vtk

def loadSTL(filenameSTL):
    readerSTL = vtk.vtkSTLReader()
    readerSTL.SetFileName(filenameSTL)
    # 'update' the reader i.e. read the .stl file
    readerSTL.Update()

    polydata = readerSTL.GetOutput()

    # If there are no points in 'vtkPolyData' something went wrong
    if polydata.GetNumberOfPoints() == 0:
        raise ValueError(
            "No point data could be loaded from '" + filenameSTL)
        return None
    
    return polydata

def vtk_show(renderer, width, height):
    render_window = vtk.vtkRenderWindow()
    render_window.SetWindowName("Simple VTK scene")
    render_window.SetSize(width, height)
    render_window.AddRenderer(renderer)

    # Create an interactor
    interactor = vtk.vtkRenderWindowInteractor()
    interactor.SetRenderWindow(render_window)
    # Initialize the interactor and start the
    # rendering loop
    interactor.Initialize()
    render_window.Render()
    interactor.Start()

def Addpoint(p, color):
    VtkSourceSphere = vtk.vtkSphereSource()
    VtkSourceSphere.SetCenter(p)
    VtkSourceSphere.SetRadius(0.1)
    VtkSourceSphere.SetPhiResolution(360)
    VtkSourceSphere.SetThetaResolution(360)
    
    VtkMapperSphere = vtk.vtkPolyDataMapper()
    VtkMapperSphere.SetInputConnection(VtkSourceSphere.GetOutputPort())

    VtkActorSphere = vtk.vtkActor()
    VtkActorSphere.SetMapper(VtkMapperSphere)
    VtkActorSphere.GetProperty().SetColor(color)
    
    renderer.AddActor(VtkActorSphere)
    
    return(p)

In [103]:
bus_vtk = loadSTL("bus.stl")
mapper = vtk.vtkPolyDataMapper()
mapper.SetInputData(bus_vtk)

actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.GetProperty().SetOpacity(0.25)

renderer = vtk.vtkRenderer()
renderer.SetBackground(1.0, 1.0, 1.0)
renderer.AddActor(actor)

p1 = Addpoint((-1.1333845630288124, 0.3581240177154541, 11.401978969573975), (1, 0, 0))

vtk_show(renderer, 800, 600)

# Seperate Internal & External Triangles Using Raycasting

In [105]:
obbTree = vtk.vtkOBBTree()
obbTree.SetDataSet(bus_vtk)
obbTree.BuildLocator()

def raycast(source, target):
    pointsVTKintersection = vtk.vtkPoints()
    code = obbTree.IntersectWithLine(source, target, pointsVTKintersection, None)

    pointsVTKIntersectionData = pointsVTKintersection.GetData()
    noPointsVTKIntersection = pointsVTKIntersectionData.GetNumberOfTuples()
    pointsIntersection = []
    for idx in range(noPointsVTKIntersection):
        _tup = pointsVTKIntersectionData.GetTuple3(idx)
        pointsIntersection.append(_tup)
        
    return(code, pointsIntersection)

In [106]:
tri_centroid

array([[-1.51806152, -0.69144652, -0.47629306],
       [-1.51806152, -0.59516935, -0.58911504],
       [-1.51806152, -0.64279433, -0.58911504],
       ...,
       [-1.69662543,  4.42957417,  0.47498579],
       [-1.80720973,  4.42120425,  0.48361361],
       [-1.99469129,  4.42586644,  0.47855952]])

In [116]:
top_view

array([[-1.13338456,  0.35812402, 11.40197897]])

In [110]:
tri_centroid[0]

array([-1.51806152, -0.69144652, -0.47629306])

In [117]:
raycast(top_view[0], tri_centroid[0])

(1,
 [(-1.4574785232543945, -0.5261492133140564, 1.3944212198257446),
  (-1.4582796096801758, -0.5283346176147461, 1.3696882724761963),
  (-1.5072999000549316, -0.6620839834213257, -0.1439894437789917),
  (-1.512351632118225, -0.6758675575256348, -0.29998141527175903),
  (-1.5125902891159058, -0.6765184998512268, -0.30734845995903015)])

In [120]:
codes = []
visible_pts = []

for pt in tri_centroid:
    
    temp = raycast(top_view[0], pt)
    
    codes.append(temp[0])
    
    if len(temp[1]) != 0:
        pass
    else:
        visible_pts.append(pt)
        
codes = np.asarray(codes)
visible_pts = np.asarray(visible_pts)

In [121]:
pcd_visible = o3d.geometry.PointCloud()
pcd_visible.points = o3d.utility.Vector3dVector(visible_pts)

o3d.visualization.draw_geometries([pcd_visible, bus_o3d])

# Compute Area of Mesh Triangles

In [20]:
tri[:, 0, :] - tri[:, 1, :]

array([[ 0.        ,  0.        , -0.28458443],
       [ 0.        ,  0.05388153, -0.05388153],
       [ 0.        ,  0.05079991,  0.        ],
       ...,
       [ 0.16539586,  0.00918484, -0.00839186],
       [ 0.08913946, -0.00826693,  0.01074722],
       [-0.15347409,  0.00842142, -0.00756812]])

In [21]:
((tri[:, 0, :] - tri[:, 1, :]) / np.linalg.norm(tri[:, 0, :] - tri[:, 1, :], axis=1)[:, None])

array([[ 0.        ,  0.        , -1.        ],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       ...,
       [ 0.99718285,  0.05537601, -0.05059508],
       [ 0.98862834, -0.09168686,  0.11919536],
       [-0.99728975,  0.05472322, -0.04917839]])

In [23]:
np.dot([1, 2, 3], [1, 2, 3])

14

In [24]:
np.dot([3, 4, 5], [1, 2, 3])

26

In [25]:
np.einsum('ij,ij->i', [[1, 2, 3],[3, 4, 5]], [[1, 2, 3], [1, 2, 3]])

array([14, 26])

In [26]:
vector_1 = tri[:, 0, :] - tri[:, 1, :]
vector_2 = tri[:, 0, :] - tri[:, 2, :]

unit_vector_1 = vector_1 / np.linalg.norm(vector_1, axis=1)[:, None]
unit_vector_2 = vector_2 / np.linalg.norm(vector_2, axis=1)[:, None]
dot_product = np.einsum('ij,ij->i',unit_vector_1, unit_vector_2)
angle = np.arccos(dot_product)

angle

array([1.57079633, 0.43175611, 2.7879506 , ..., 0.07507961, 2.83089987,
       1.49721104])

# Adaptive Mesh Triangles Subdivision